const JAMBONES_TTS_TRIM_SILENCE = process.env.JAMBONES_TTS_TRIM_SILENCE;
const JAMBONES_DISABLE_TTS_STREAMING = process.env.JAMBONES_DISABLE_TTS_STREAMING;
const JAMBONES_DISABLE_AZURE_TTS_STREAMING = process.env.JAMBONES_DISABLE_AZURE_TTS_STREAMING;
const JAMBONES_EAGERLY_PRE_CACHE_AUDIO = process.env.JAMBONES_EAGERLY_PRE_CACHE_AUDIO;
const JAMBONES_AZURE_ENABLE_SSML = process.env.JAMBONES_AZURE_ENABLE_SSML;

const JAMBONES_HTTP_PROXY_IP = process.env.JAMBONES_HTTP_PROXY_IP;
const JAMBONES_HTTP_PROXY_PORT = process.env.JAMBONES_HTTP_PROXY_PORT;
const JAMBONES_TTS_CACHE_DURATION_MINS =
  (parseInt(process.env.JAMBONES_TTS_CACHE_DURATION_MINS) || 4 * 60) * 60; // cache tts for 4 hours

const TMP_FOLDER = process.env.JAMBONES_TMP_FOLDER || '/tmp';

const HTTP_TIMEOUT = 5000;

// Azure TTS timeout parameters
const JAMBONES_AZURE_SPEECH_SYNTHESIS_FRAME_TIMEOUT_INTERVAL =
  parseInt(process.env.JAMBONES_AZURE_SPEECH_SYNTHESIS_FRAME_TIMEOUT_INTERVAL) || 15000; // default 10 seconds
const JAMBONES_AZURE_SPEECH_SYNTHESIS_RTF_TIMEOUT_THRESHOLD =
  parseFloat(process.env.JAMBONES_AZURE_SPEECH_SYNTHESIS_RTF_TIMEOUT_THRESHOLD) || 4; // default RTF threshold of 4

module.exports = {
  JAMBONES_TTS_TRIM_SILENCE,
  JAMBONES_DISABLE_TTS_STREAMING,
  JAMBONES_DISABLE_AZURE_TTS_STREAMING,
  JAMBONES_HTTP_PROXY_IP,
  JAMBONES_HTTP_PROXY_PORT,
  JAMBONES_TTS_CACHE_DURATION_MINS,
  JAMBONES_EAGERLY_PRE_CACHE_AUDIO,
  TMP_FOLDER,
  HTTP_TIMEOUT,
  JAMBONES_AZURE_ENABLE_SSML,
  JAMBONES_AZURE_SPEECH_SYNTHESIS_FRAME_TIMEOUT_INTERVAL,
  JAMBONES_AZURE_SPEECH_SYNTHESIS_RTF_TIMEOUT_THRESHOLD
};
